### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Raclamusi** [Siv3D/siv3d.github.io#1]
「クラス一覧」のページの誤植を2つ見つけたので、報告します。

- detail: → detail::
https://github.com/Siv3D/siv3d.github.io/blob/6de7179f2af489073e0a169eb1758c1c7146ac34/api/classes/index.html#L2424

- Serialize → Serializer
https://github.com/Siv3D/siv3d.github.io/blob/6de7179f2af489073e0a169eb1758c1c7146ac34/api/classes/index.html#L3184

---

**質問**
ここには PR は投げない方がいいですか？（ローカルで自動更新されてそうなファイルがあるので）

**Comment by Reputeless** [comment]
Duplicate of https://github.com/Siv3D/siv3d.docs/issues/69

【今後の利用者への案内】
Siv3D 公式サイトへの Issues は https://github.com/Siv3D/siv3d.docs をご利用ください。
